
// Code pour les IMPORTS : ----------------------------------------------------------------------------------------------------------------------------------//

import type { Metadata } from "next"; // metada pour les métadonnées 
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"; // import du fichier CSS 
import Banner from "./components/Banner"; // import composant Banner
import MessagesBar from "./components/MessagesBar";  // import de la MessagesBar
import Footer from "./components/Footer"; // import du footer

//--------------------------------------------------------------------------------------------------------------------------------------------------------------//
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });




// CODE pour les métadonnées : -------------------------------------------------------------------------------------------------------------------------------//

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//-------------------------------------------------------------------------------------------------------------------------------------------------------------//




export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
          <link rel="preconnect" href="https://fonts.googleapis.com"/>
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous"/>
          <link href="https://fonts.googleapis.com/css2?family=Bangers&family=Lilita+One&display=swap" rel="stylesheet"/>
      </head>
      <body
        className="tracking-wider"
        // {`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Banner />
        <MessagesBar />
       
          <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
